import type { Metadata } from "next";
import React from "react";
import Navbar from "./components/navbar";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Apex Team Tools | Cuboir",
  description: "Generated by create next app",
};

interface IRootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: IRootLayoutProps) {
  return (
    <html className="h-full bg-gray-100" lang="en">
      <UserProvider>
        <body className="h-full">
          <ToastContainer />
          <div className="min-h-full">
            <Navbar />
            <main>{children}</main>
          </div>
        </body>
      </UserProvider>
    </html>
  );
}
